services:
  cryptoscope-api:
    build:
      context: ./CryptoScopeAPI
      dockerfile: Dockerfile
    ports:
      - "5218:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - cryptonet


  cryptoscope-ui:
    build:
      context: ./CryptoScopeUI
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - cryptoscope-api
    networks:
      - cryptonet

networks:
  cryptonet:
    driver: bridge